### ISSUE TITLE
How to set endpoint to send transaction on mainnet?

### ISSUE THREAD

**Issue by deepcola** [nebulasio/neb.py#4]

**Comment by yupnano** [comment]
please try this:
```python
neb = Neb("https://mainnet.nebulas.io")
```

**Comment by deepcola** [comment]
OK,thanks.But package on PyPl looks like not updated.Could I just put github files to folder /nebpysdk and use it?

**Comment by deepcola** [comment]
OK,thanks.But package on PyPl looks like not updated.Could I just put github files to folder /nebpysdk as update and use it?
