### ISSUE TITLE
I can see the txhash,but there is no recording in the testnet 

### ISSUE THREAD

**Issue by CCColby** [nebulasio/neb.py#5]

**Comment by yupnano** [comment]
That might because there is something wrong in your transaction, such as zero balance, low gasPrice & gasLimit, improper nonce.
Please paste your transaction details here.

**Comment by CCColby** [comment]
thanks !!!  I find the reason,low gasPrice cause this problem,it works well now.Thanks for your answer!!!

**Comment by yupnano** [comment]
You are welcome!

**Comment by pramanikshubham** [comment]
How I can increase my gaslimit
 ff462ac6cd3eaa85c6f80101fd97bebf3dbcece4e386a7348bf029662ac99645

**Comment by yupnano** [comment]
https://github.com/nebulasio/explorer/issues/65
